name: ROS2 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y python3-colcon-common-extensions python3-rosdep
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
    
    - name: Build ROS2 package
      run: |
        . /opt/ros/humble/setup.sh
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
        
    - name: Run tests
      run: |
        . /opt/ros/humble/setup.sh
        . install/setup.sh
        colcon test
        colcon test-result --verbose
